### ISSUE TITLE
possible problem with utf8

### ISSUE THREAD

**Issue by elf-pavlik** [bevry/feedr#1]
i take data from this json: http://ouisharefest.com/translations/el.json which includes nested

```
 { el: { sections: { "speakers":"Ομιλητές" } } }
```

but in template in docpad i get:  Ομιλ��τές with

```
<%= @feedr.feeds.el.el.sections.speakers  %>
```

in docpad coffee:

```
  plugins:                                                                                                      
    feedr:                                                                                                      
      feeds:                                                                                                    
        el:                                                                                                     
          url: 'http://ouisharefest.com/translations/el.json'                                                   
          cache: false
```

repo: https://github.com/OuiShare/ouisharefest/commit/22dc28b549aa2a163ddad2a6a3aff04be81c6ce8
